### ISSUE TITLE
Failed to Load Assembly

### ISSUE THREAD

**Issue by robbratton** [mikehadlow/AsmSpy#12]
I'm trying to use AsmSpy against a working application. I get Failed to Load Assembly on every dll.

C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\ClinicalWorkflow\ClinicalModel\Web
\bin>asmspy .
Check assemblies in:
C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\ClinicalWorkflow\ClinicalModel\Web
\bin

Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\ActiveDirectoryAuthentication.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\ClinicalModel.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\LegacyDataManager.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\LegacyWcfServiceContracts.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\MaintenanceWeb.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\MemoryCache.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Newtonsoft.Json.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\NLog.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.DataAccess.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Legacy.CoreService.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Legacy.ExamService.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Security.ADUtilitiesLegacy.exe'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Security.AuthorizationContract.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Security.Cryptography.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Security.TicketingDataAccess.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Security.Web.Configuration.dll'
Failed to load assembly: 'C:\Users\robert.bratton\Downloads\FFIReporting-3.5.0.918-BETA USE ONLY\www\production\Clinical
Workflow\ClinicalModel\Web\bin\Poiesis.ClinicalModel.Security.WebAppModule.dll'
Detailing only conflicting assembly references.

Here are the DLLs in the folder:
ActiveDirectoryAuthentication.dll
ClinicalModel.dll
LegacyDataManager.dll
LegacyWcfServiceContracts.dll
MaintenanceWeb.dll
MemoryCache.dll
Newtonsoft.Json.dll
NLog.dll
Poiesis.ClinicalModel.DataAccess.dll
Poiesis.ClinicalModel.Legacy.CoreService.dll
Poiesis.ClinicalModel.Legacy.ExamService.dll
Poiesis.ClinicalModel.Security.AuthorizationContract.dll
Poiesis.ClinicalModel.Security.Cryptography.dll
Poiesis.ClinicalModel.Security.TicketingDataAccess.dll
Poiesis.ClinicalModel.Security.Web.Configuration.dll
Poiesis.ClinicalModel.Security.WebAppModule.dll

**Comment by mikehadlow** [comment]
Permissions problem?

On Tue, Feb 17, 2015 at 6:14 PM, Robert E. Bratton <notifications@github.com

**Comment by shift-evgeny** [comment]
I got this when trying to load a 64-bit assembly. AsmSpy is compiled as 32-bit for some reason. If I compile it as AnyCPU the error goes away.

**Comment by mikehadlow** [comment]
Cool. Thanks for letting me know. I'll try and get an AnyCPU version released.

**Comment by mikehadlow** [comment]
Is this answered? Can I close?

**Comment by mikehadlow** [comment]
Closing
