### ISSUE TITLE
Chocolatey package please?

### ISSUE THREAD

**Issue by serbrech** [mikehadlow/AsmSpy#14]
Self explanatory title

**Comment by mikehadlow** [comment]
Very good idea. Do you want to submit a pull request?

**Comment by serbrech** [comment]
I'd love to. coming soon :)


Stéphane Erbrech

**Comment by rahulpnath** [comment]
@mikehadlow One of the review comments from chocolatey was to have the copyright in nuspec to be 'Change nuspec copyright to "Suteki Ltd"'. Is that how you wanted to keep it? Just double checking

**Comment by mikehadlow** [comment]
Yes, that would be fine. Thanks Rahul!

**Comment by rahulpnath** [comment]
[Asmspy chocolatey packageis](https://chocolatey.org/packages/asmspy/1.0.0) available now!
This is the latest version of today. In case of any new updates will start versioning and releasing it

cc @mikehadlow @serbrech

**Comment by mikehadlow** [comment]
Fantastic work Rahul. Many thanks for this. I'll add a link to the readme.
