### ISSUE TITLE
output in another format

### ISSUE THREAD

**Issue by dhiogoacioli** [mikehadlow/AsmSpy#18]
I have a solution with hundreds of projects. and I can not see any references because the cmd limits the result.

**Comment by mikehadlow** [comment]
Why not just pipe the output to file?

    asmspy.exe > output.txt

**Comment by rahulpnath** [comment]
Yes outputting to a text file should help. Have used it for a project with around 145 projects. Think this issue should be closed @dhiogoacioli ?
