### ISSUE TITLE
Improve argument handling. Update usage statement

### ISSUE THREAD

**Issue by koolraap** [mikehadlow/AsmSpy#19]
The usage statement currently says:

    Console.WriteLine("AsmSpy <directory to load assemblies from> [all]");

It should include the nonsystem argument:

    Console.WriteLine("AsmSpy <directory to load assemblies from> [all|nonsystem]");

It'd also be nice to add /? -? -help --help parameter handling. The app respsonds with "Directory: '/? ' does not exist" which is annoying when it doesn't occur to me (maybe others) to run AsmSpy without parameters.

Further niceness could be achieved by making the parameters a bit more standard, /a, /n, /all, /nonsystem. That'd make argument order irrelevant.

**Comment by mikehadlow** [comment]
Thanks for the suggestion. I'd be very happy to accept a pull request for these changes ;)

**Comment by koolraap** [comment]
Challenge accepted :-) Been meaning to try Git for ages.
