### ISSUE TITLE
Definition of console colours

### ISSUE THREAD

**Issue by mikiest** [mikehadlow/AsmSpy#28]
Can we have a quick definition of the logging colours, maybe in the README.md?

i.e.:
- Green
- Blue
- Yellow
- Red

It looks a bit confusing at the moment (except green..).

**Comment by mikehadlow** [comment]
Very happy to accept a pull request for this.

**Comment by mikiest** [comment]
Well I don't actually know what they mean .. hence the issue :o

**Comment by flaub** [comment]
https://github.com/mikehadlow/AsmSpy/blob/master/AsmSpy/ConsoleVisualizer.cs#L95

Looks like deciphering this line will give us the answer.

**Comment by mikehadlow** [comment]
Readme has been updated.
