### ISSUE TITLE
Wish - Splitting the project to enable other ways of reporting

### ISSUE THREAD

**Issue by michaelthyregod** [mikehadlow/AsmSpy#34]
Hi there.

Been looking at the code, and did some changes in my fork where I split out the console specific out into a new project. The idea is to enable the option to add other engines as reporting output - it could be msbuild task, Teamcity task or something similar.

Reason for this is that I think the base code is exactly what I'm looking for, but I need to report while building in Visual studio based on a whitelist (I will add that later)

Also added a new switch to enable filtering on the referenced assemblies in the console reporting.

You can look here -and if you like it I can do a PR

https://github.com/michaelthyregod/AsmSpy

Also consider to maket it 2 nuget packages and upload these to nuget.org - since it is a cool simple little tool with lots of usage scenarios if possible to reference it.

Should you be interrested I can also add build output task with ilMerge that merges the base assembly into the console output exe file - so it is still only 1 exe file as output.

**Comment by mikehadlow** [comment]
Thanks for this, it sounds like an excellent idea. So long as it doesn't impact people who just want to download/choco install the commnad line tool I'm very much in favour of it. The ILMerge approach sounds appropriate. So long as you're prepared to do the work, go for it!

**Comment by michaelthyregod** [comment]
Awesome - I will do the described above and then do a PR to your branch this weekend - then it's all up to you :-) You will be hearing from me soon :-) Have a good weekend.

**Comment by mikehadlow** [comment]
Can we close this?
