### ISSUE TITLE
Feature request: only check a single assembly

### ISSUE THREAD

**Issue by sjoerd222888** [mikehadlow/AsmSpy#41]
Can you add an option where I can pass a single DLL file instead of a complete directory? 

Use case is having a large project with a lot of DLLs and I already know what DLL has a problem (e.g. missing dependency).

**Comment by mikehadlow** [comment]
Happy to take a PR if you want to implement it.

**Comment by apuchkov** [comment]
I just submitted a PR #45 for this feature.

**Comment by mikehadlow** [comment]
Merged PR #45
