### ISSUE TITLE
Option to honor bindingRedirect in App.config / Web.config

### ISSUE THREAD

**Issue by pfeigl** [mikehadlow/AsmSpy#54]
We are using AsmSpy as part of our build process to make sure we didn't miss out adding important references.

One thing we often run into is version mismatches which we actually fixed using bindingRedirects, but AsmSpy is still reporting them.

Is it possible to extend AsmSpy to honor bindingRedirects?

**Comment by mikehadlow** [comment]
Hi  Philipp,
That's a good idea. I don't have time to implement it right  now, but I'd be more than happy if you wanted to submit a pull request.
Thanks,
Mike

**Comment by pfeigl** [comment]
Sent a PR btw for this :)

**Comment by pfeigl** [comment]
This should btw also close #7, because this seems to be still open because of the required check for the binding redirects
