### ISSUE TITLE
Is it bad to have references to GAC assemblies?

### ISSUE THREAD

**Issue by vorou** [mikehadlow/AsmSpy#57]
Hey, thanks for a great tool.

What do you typically do when the tool reports assemblies from GAC? I see two types of assemblies reported: system (which you can hide w/ -n switch) and non-system. 

I guess I could try to install the non-system ones from NuGet instead, which will make it easier to deploy and to configure a new dev box (I won't have to install some SDKs).
Am I right that there is nothing you can do about the system ones and they are outputted just for the sake of completeness?

**Comment by mikehadlow** [comment]
Yes, that's right, the Base Class Library (BCL) Assemblies (the System.* ones) are usually held in the GAC. What you get depends on what versions of .NET you have installed on your system. NuGet is now the preferred repository for everything that doesn't come out-of-the-box, including some System.* assemblies. You generally don't want to install assemblies in the GAC.
