### ISSUE TITLE
Zip file does not exist in artifact listing

### ISSUE THREAD

**Issue by b169** [mikehadlow/AsmSpy#58]
Hi,
There's no zip archive on https://ci.appveyor.com/project/rahulpnath/asmspy/branch/master/artifacts

Possibly, because of AppVeyor's 6 months retention policy

![image](https://user-images.githubusercontent.com/5102072/55722473-1b449700-5a0f-11e9-9476-bae3d580d190.png)

**Comment by mikehadlow** [comment]
Thanks @b169, I think you're right, I just kicked off a new AppVeyor build to re-create it. The zip file is back now.

Sorry it's taken me a while to get around to this :(

For future reference the NuGet package is also a zip file (just change the extension to .zip), you can find the AsmSpy.exe buried somewhere in there.

**Comment by b169** [comment]
Yep, found it. Thanx!
