### ISSUE TITLE
Feature request: Output structured report

### ISSUE THREAD

**Issue by patriksvensson** [mikehadlow/AsmSpy#59]
Would be nice if there was an option to output the report as structured data such as XML. That way it would be easier to post-process the report.

If this is something that you would find useful, I would be happy to contribute a pull request for this.

**Comment by mikehadlow** [comment]
We currently support outputting the dependency graph as a DGML file with the dgml option (see the readme), but I agree that that's a somewhat specialised format. If you'd like to go ahead and implement an XML (and/or JSON?) output that would be much appreciated.

**Comment by patriksvensson** [comment]
@mikehadlow Perfect! I've already started on this since I needed it, so I will make sure I contribute it back as a pull request then 😄

**Comment by patriksvensson** [comment]
Closed via #60
