### ISSUE TITLE
Move referencedStartsWith (and possibly also SkipSystem) from Visualizer to Analyzer

### ISSUE THREAD

**Issue by pfeigl** [mikehadlow/AsmSpy#62]
Right now there are options (in my case specifically `referencedStartsWith`) which are are only considered when generating the output.

This has two major drawbacks:
* Handling of the options has to be implemented in any visualizer
* Non-visualization topics are not handled at all

My specific problem:
There is the option `failOnMissing` which makes sure that AsmSpy exits with a negativ exit code when assembly problems could be identified.
This exit-code is generated based on the analyzation-result.
However the analyzer does not honor `referencedStartsWith` and has all references available - even those which should be ignored. This ultimately ends in a situation, where the visualizer shows no problems but the tool exits with exit-code `-1`.

I'd happily provide a PR on whatever we identify as a solution for this, which is probably one of the following:
1. The failOnMissing test honors `referencedStartsWith` on it's own (meaning it pretty much does the same as all the visualizers do already)
2. The analyzer just does not include ignored assemblies in the result and follow-up code therefor simply does not have to handle them (i.e. visualization)
3. The analyzer includes them but the Enum `AssemblySource` is extended with an `Ignored` value which can than be evaluated by others.

I think the same might also be true for the `SkipSystem` option.
The `OnlyConflicts` on the other hand is something I'd keep on the visualizer, because this option actually only configures, how the result should look like - it does not change the behavior in itself.

Comments, ideas? :-)

// Edit: My personal preference is 2)

**Comment by pfeigl** [comment]
PR which option 2) created. Based on a final understanding this can either be merged or changed.

**Comment by mikehadlow** [comment]
Agreed. I like option 2 as well. Thanks for this @pfeigl, I'll take a look at your PR.

**Comment by mikehadlow** [comment]
Fixed
