### ISSUE TITLE
Create UnitTests

### ISSUE THREAD

**Issue by pfeigl** [mikehadlow/AsmSpy#64]
Sorry for creating this issue - but I feel I have to :flushed:

I've done a few small changes meanwhile on AsmSpy and every time I change something I'm unsure if those changes might affect someone in a negativ way or even bring a breaking change in.

I tried my best testing everything manually as good as possible, but ultimately I (and probably others) mostly test if changes they need themselves work as expected. I.e. I'm not using the exports and thus am not testing those too much.

I guess the only solution to this is to have a solid UnitTest suite which covers atleast the major things.

Even a small integration test suite might do wonders, like testing validating the whole output or checking the overall exit code of the tool.

(I'm not having the time right now to work on this, but thought it might be a good thing to have it looked. Possibly some other community member can work on this?)

**Comment by mikehadlow** [comment]
Agreed, a unit test suite would be very nice to have.

**Comment by mikehadlow** [comment]
Added in the latest commit.
